Homework 12. Локальная разработка и тестирование Ansible ролей и плейбуков
Otus-DevOps-2018-02/max2l_infra pull request #14
Opened 2018-04-19 13:02 UTC by max2l

# Выполнено ДЗ № 12

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Установлен и настроен VirtualBox и Vagrant
 - Сознана конфигурация `Vagrant` для разворачивания двух виртуальных машин
 - Настроено взаимодействие `Vagrant` c ролями `Ansible` которые были создамы в педиыдушем ДЗ
 - Доработаны роли `Ansible` для работы с `Vagrant`
 - Произведено тестирование применения ролей на запушеных VM.
 - Произведена параметризация роли app для работы ПО из под любого пользователя. 
 - Настроена конфигурация `Nginx` для работы с приложенем `Puma`
 - Настроено тестирование Ansible ролей используя ПО `Molecule
 - Роль `db` вынесена в отвельный репозиторий `https://github.com/max2l/db_role_for_mongo`
 - Настроено тестирование вынесеной роли с помошью `Molecule` в облаке `GCP`
 - Настроена отправка сообщений в канал [Slack|https://devops-team-otus.slack.com/messages/C6U5JSKSQ/] 

## Как запустить проект:
 - Проверить скачивание образа виртуальной машины `box` и статуса виртуальных машин можно командами
```
vagrant box list
vagrant status
```
 - Соедениться с запущенными виртуальными машинами можно командами 
```
vagrant ssh appserver
vagrant ssh dbserver
```
 - Применить роли на запушеных VM можно командами 
```
vagrant provision dbserver
vagrant provision appserver
```
 - Создать и удалить VM можно командами
```
vagrant up
vagrant destroy -f
```
## Как проверить работоспособность:
 - После запуска проекта командой `vagrant up` приложение должно быть доступно по ссылке  http://10.10.10.20

## PR checklisk
 - [x] Выставил label homework-12 с номером домашнего задания
 - [x] Выставил label ansible с темой домашнего задания

2018-04-22 20:40 UTC, sedovandrew requested changes
Привет! Посмотрел задание. Нашёл опечатку, а вот тестирование порта, на котором слушает база данных не нашёл. Ещё появился вопрос. Зачём оставил роль db, если ты её вынес в отдельный репозиторий?

2018-04-22 20:40 UTC, sedovandrew commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
Посмотри, что не так!

2018-04-22 20:40 UTC, sedovandrew commented on ansible/roles/db/molecule/default/tests/test_default.py
> +    assert config_file.is_file
Не нашёл теста для проверки нужного порта, на котором висит база данных.

2018-04-22 20:40 UTC, sedovandrew commented on ansible/roles/db/molecule/default/tests/test_default.py
> +    assert config_file.is_file
В https://github.com/max2l/db_role_for_mongo тоже этого теста нет.

2018-04-22 20:44 UTC, sedovandrew commented on ansible/roles/db/molecule/default/tests/test_default.py
> +    assert config_file.is_file
Забавно, ты тест сделал, а потом его удалил. :-)

2018-04-23 11:40 UTC, max2l commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
Я специально оставил два тега, для работы я динамическими и статическими инвентори, что бы проще было переключаться между ними. мне необходимо оставить только теги для работы только с одним инвентори?

2018-04-23 11:56 UTC, sedovandrew commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
Я понял для чего два тега, просто здесь должен быть `tag_reddit-app`, а не `tag_reddit-db`

2018-04-23 12:21 UTC, max2l commented
Привет! Удалил роль роль db из этого репозитория и добавил тест прослушивания порта базой MongoDB для этой роли в удаленном репозитории.

2018-04-23 14:07 UTC, max2l commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
Не заметил очевидную вещь, сорри 😀 спасибо за подсказку

2018-04-23 16:29 UTC, max2l commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
Поправил тег

2018-04-23 16:49 UTC, sedovandrew commented on ansible/playbooks/app.yml
> +    - tag_reddit-db
:+1:

2018-04-23 16:53 UTC, sedovandrew approved these changes

2018-04-24 10:42 UTC, max2l commented
Спасибо!

2018-04-24 10:42 UTC, merged