Play travis
Otus-DevOps-2018-02/max2l_infra pull request #2
Opened 2018-03-07 10:22 UTC by max2l

В данном задании настроено взаимодействие интеграционного канала Slack c GitHub и интеграция TravisCI,  GitHub и Slack. Так же был зашифрован token для взаимодействия между TravisCI и Slack.

При выполнении commit в репозиторий GitHub должно придти уведомление о нем в интеграционный канал Slack, так же должна запуститься сборка и тестирование проекта в  TravisCI. 

Проверить работу проекта можно путем анализа сообщений приходящих в интеграционный канал Slack. В нем будут отображаться сообщения о всех commits из репозитория max2l_infra и уведомления о удачных или неудачных тестах из TravisCI.

Также я: 
  - Выставил label Travis с номером домашнего задания
  - Выставил label Homework-3 с номером домашнего задания

2018-03-17 12:08 UTC, sedovandrew requested changes
Максим, привет! Всё выглядит здорово. Единственное, что я заметил, что у тебя потерялся шаблон `.github/PULL_REQUEST_TEMPLATE.md`, что внёс @vitkhab в твой репозиторий: https://github.com/Otus-DevOps-2018-02/max2l_infra/pull/1/commits/ff3f29766405bfeddefef52af7a8b1826a000009 , когда делал approve.

2018-03-19 07:23 UTC, max2l commented
Добрый день! Случайно снес шаблон и видимо добавил не корректный файл. Я объединил master branch c этой веткой. md5sum файла шаблона в этой ветке стала совпадать с аналогичным файлом добавленным пользователем @vitkhab. Надеюсь я сделал все правильно. Сейчас этот шаблон корректный?

2018-03-20 01:52 UTC, sedovandrew commented
Максим, сейчас всё здорово!! Спасибо!!

2018-03-20 01:52 UTC, sedovandrew approved these changes

2018-03-20 05:38 UTC, max2l commented
Спасибо!

2018-03-20 05:38 UTC, merged